### ISSUE TITLE
Chat Module

### ISSUE THREAD

**Issue by itsmfknlucy** [minvalencia/iteams#170]
Create chat module implementation of iTEAMS

Template
1. iTEAMS Messages Template

Module List
1. Message Room (Groups, Conversations, and Task Channel)
2. Message (Messages)
3. Message Participants (Members/Users involved in every chat, blocked users, muted chat rooms, hidden chat rooms, group creators, and group admins)
4. Message Notification (Notifications of messages, group updates, and channel updates)

Affected Tables
1. MSGROOM
2. MSGS
3. MSGPRTCPNTS
4. MSGNOTIF

Stored Procedures
1. SP_MsgRoomCRUD
2. SP_MsgsCRUD
3. SP_MsgPrtcpntsCRUD
4. SP_MsgNotifCRUD

**Comment by minvalencia** [comment]
refactor message module:
- fixed the right pane and left page
- added sendMessage functionality
